### PR TITLE
Fix nlohmann-json library in Android image

### PR DESCRIPTION
**Pull request by AaronVanGeffen**

### CODE REVIEW

**Review by janisozaur — COMMENTED** [review]
Not too fond of this change. You'd have to end up adding the host includes to the search path, that invites problems when you accidentally start including other headers from libraries installed on host in ever-so-slightly different versions. No idea why they are being installed in the first place.

**Comment by AaronVanGeffen** [comment]
@janisozaur I am open to suggestions. Clearly, the current image isn't working. Given that #4 is using the same approach, this seemed like the obvious solution.

**Comment by janisozaur** [comment]
Right. My bad, should've heed same advice. Ideally both those should use path relevant to toolchain (mingw) or when lacking/not known (Android) use path custom enough that's not going to collide with other libs.

In other words: leave it as is and add the custom search path to project.

**Comment by AaronVanGeffen** [comment]
I'm a bit puzzled by your answer. Should I close the PR and add a path to the Android project? If the latter, I'm not sure what you have in mind. In that case, could you take care of it?

**Comment by janisozaur** [comment]
Yeah, change the project setup instead. I can try updating it if @mwnciau doesn't beat me to it.

**Pull request closed without merging**
